### PR TITLE
Fix trunc_sat instr parsing

### PR DESCRIPTION
**Pull request by osa1**

### CODE REVIEW

**Review by nomeata — COMMENTED** [review]
What’s wrong with using lambda case here? The change in coding style makes it hard to see the real change…

Ah, it’s changing `getWord8` to `getULEB128 32`, right?

**Comment by osa1** [comment]
> What’s wrong with using lambda case here? The change in coding style makes it hard to see the real change…

Nothing wrong with lambda case. I had a debug print printing the scrutinee, that's why I bound it to a variable. I reverted it now.

> Ah, it’s changing getWord8 to getULEB128 32, right?

Yes.

**Review by nomeata — APPROVED** [review]

**Comment by nomeata** [comment]
Surprised this wasn’t caught in the wasm test suite. Maybe these things only occur in the files we skip because of incomplete Float support or something.

If you don’t mind I’ll wait with merging until CI works again.

**Comment by osa1** [comment]
It is caught by the Wasm test suite, but IIRC we skip the file that tests this. I found this while running the Wasm test suite.

**Comment by nomeata** [comment]
Yuck, why does github not offer the “update branch” button even on repos without strict merges.

**Comment by osa1** [comment]
It turns out I removed lambda case to be able to annotate type of the return value. Without the annotation this doesn't type check.

@nomeata ready now.

**Pull request merged**
