### PR TITLE
Fix getMemoryOp and getMathPrefix parser error msgs

### PR DESCRIPTION
**Pull request by osa1**
Also replaced `error` with `fail` for consistency with the rest of the
code.

### CODE REVIEW

**Review by nomeata — APPROVED** [review]

**Comment by osa1** [comment]
@nomeata I don't have push access to this repo yet (it turned out to be tricky for some reason ...), could you merge this please?

**Comment by nomeata** [comment]
I’ll wait for CI to work again, then will do of course!

**Comment by nomeata** [comment]
sorry, botched the merge

**Comment by nomeata** [comment]
Merged as 12f6ba8

**Pull request closed without merging**
